# Generated by Django 5.0.6 on 2024-05-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetail',
            fields=[
                ('Student_ID', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Middle_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('Birth_Date', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Entry_Year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
