# Generated by Django 5.0.6 on 2024-05-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_doctordetail_delete_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordetail',
            old_name='Student_ID',
            new_name='Admin_ID',
        ),
        migrations.RenameField(
            model_name='doctordetail',
            old_name='Entry_Year',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='doctordetail',
            old_name='published_date',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='doctordetail',
            name='Email',
        ),
        migrations.AddField(
            model_name='doctordetail',
            name='User_Name',
            field=models.CharField(default='default_value_here', max_length=100),
        ),
    ]
