# Generated by Django 5.0.6 on 2024-05-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_student_id_doctordetail_admin_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetail',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='User_Name',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
